### ISSUE TITLE
TE under CPM3 doesn't use the screen size bytes to determine rows and columns on startup, eg as VT100DYN

### ISSUE THREAD

**Issue by riwide** [MiguelVis/te#2]
TE under CPM3 doesn't use the screen size bytes to determine rows and columns on startup, eg as VT100DYN

**Comment by MiguelVis** [comment]
Hi @riwide.

That's a good idea. I will have into account for new releases as a configuration option.

**Comment by MiguelVis** [comment]
Done in v1.70:

```
# Screen height: 8..255 or auto for CP/M 3
#screen.rows = 25

# Screen width: 64..255 or auto for CP/M 3
#screen.columns = 80
```
