### ISSUE TITLE
Capabilities?, Compiler?

### ISSUE THREAD

**Issue by ve7it** [MiguelVis/te#3]
I dont see any description of the file size capacity of the editor. Can it edit files > TPA? I have several source and listing files > 80K. Can the editor page through these files? Also, I didnt see a mention of the compiler used to build this editor. Perhaps that could be added to either the makefile or the readme.
Thank you for sharing
Lawrence

**Comment by MiguelVis** [comment]
Hi @ve7it.

The file is loaded into the TPA and edited there.

The compiler used is MESCC, my own Small-C derived compiler:

[https://github.com/MiguelVis/mescc](https://github.com/MiguelVis/mescc)

It's K&R style, no structures, etc. but it suits all my needs.

**Comment by MiguelVis** [comment]
Done in v1.70.
