### ISSUE TITLE
^K^B/^K selects lines, not blocks

### ISSUE THREAD

**Issue by ProgrammingCube** [MiguelVis/te#7]
In wordstar, the KB and KK commands select blocks of text from cursor to cursor, but TE, specifically the VT100 build, selects the LINES of KB to KK, which makes it slightly inconvenient to delete parts of lines, as it cannot do so.
Is there a command I am missing?

**Comment by MiguelVis** [comment]
Hi @ProgrammingCube.

TE can select whole lines only.
